"""empty message

Revision ID: 3740e7a34a82
Revises: 0492aec2cf18
Create Date: 2020-07-09 11:17:11.745354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3740e7a34a82'
down_revision = '0492aec2cf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
